---
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options
# Use MegaLinter for linting]
include:
  - project: "ipsec/citemplates"
    ref: master
    file: "/linting/megalinter-dotnet.yml"

stages:
  - linting
  - test

megalinter:
  extends: .megalinter-minimal
  variables:
    DISABLE_LINTERS: SPELL_CSPELL,ARM_ARM_TTK
